### ISSUE TITLE
Error: Cannot find module './build/Release/shell'

### ISSUE THREAD

**Issue by rebelliard** [pierot/grunt-fabric-deploy#2]
I can't get the task to run, as it depends on `execSync` and that project seems to be [failing](https://github.com/cri5ti/grunt-shell-spawn/issues/29) on Mac OS X.

    $ grunt deploy
    Loading "deploy.js" tasks...ERROR
    >> Error: Cannot find module './build/Release/shell'
    Warning: Task "deploy" not found. Use --force to continue.
    Aborted due to warnings.

**Comment by pierot** [comment]
I updated the exec functionality with a new version bump [0.0.6](https://www.npmjs.com/package/grunt-fabric-deploy)
https://github.com/pierot/grunt-fabric-deploy/commit/e6d47df22508f101541eb233fdb1c47170edd131
